Repository bounswe/bounswe2019group2, pull requests merged in 2019-05, with the labels that each got.

#80 Add auth api
  practice-app/api/admin.py
  practice-app/api/migrations/__init__.py
  practice-app/api/serializers.py
  practice-app/api/urls.py
  practice-app/api/views.py
  practice-app/practice/settings.py
  practice-app/practice/urls.py
  practice-app/requirements.txt
Labels: Priority: Medium, Type: Backend

#86 Adding Test Cases for Auth Api
  practice-app/api/tests.py
  practice-app/api/views.py
Labels: Priority: Low, Status: In Progress, Type: DevOps

#92 implemented total profit calculation
  practice-app/api/urls.py
  practice-app/api/views.py
  practice-app/practice/settings.py
Labels: Status: In Progress, Type: Backend

#91 Parity list added
  practice-app/api/tests.py
  practice-app/api/urls.py
  practice-app/api/views.py
Labels: Status: In Progress, Type: Backend

#100 1.3.4 Investment profit calculation and history generation
  practice-app/api/management/commands/generatehistory.py
  practice-app/api/management/equipment.json
  practice-app/api/urls.py
  practice-app/api/views.py
Labels: Type: Backend

#97 [WIP] Prepare for deployment
  .travis.yml
  practice-app/.gitignore
  practice-app/backend/.gitignore
  practice-app/backend/Dockerfile
  practice-app/backend/api/__init__.py
  practice-app/backend/api/admin.py
  practice-app/backend/api/apps.py
  practice-app/backend/api/management/__init__.py
  practice-app/backend/api/management/commands/__init__.py
  practice-app/backend/api/management/commands/generatedevelopmentdata.py
  practice-app/backend/api/management/commands/generatehistory.py
  practice-app/backend/api/management/equipment.json
  practice-app/backend/api/models.py
  practice-app/backend/api/serializers.py
  practice-app/backend/api/tests.py
  practice-app/backend/api/urls.py
  practice-app/backend/api/views.py
  practice-app/backend/manage.py
  practice-app/backend/practice/__init__.py
  practice-app/backend/practice/cron.py
  practice-app/backend/practice/production_settings.py
  practice-app/backend/practice/settings.py
  practice-app/backend/practice/urls.py
  practice-app/backend/practice/wsgi.py
  practice-app/backend/requirements.txt
  practice-app/docker-compose.yml
  practice-app/frontend/assets/css/bootstrap.min.css
  practice-app/frontend/assets/css/light-bootstrap-dashboard.css
  practice-app/frontend/assets/css/pe-icon-7-stroke.css
  practice-app/frontend/assets/fonts/Pe-icon-7-stroke.eot
  practice-app/frontend/assets/fonts/Pe-icon-7-stroke.svg
  practice-app/frontend/assets/fonts/Pe-icon-7-stroke.ttf
  practice-app/frontend/assets/fonts/Pe-icon-7-stroke.woff
  practice-app/frontend/assets/js/bootstrap.min.js
  practice-app/frontend/assets/js/jquery.3.2.1.min.js
  practice-app/frontend/assets/js/light-bootstrap-dashboard.js
  practice-app/frontend/index.html
  practice-app/nginx.conf
Labels: Status: In Progress, Type: DevOps

#113 Tests for 1.3.4 and 1.3.5
  practice-app/backend/api/tests.py
  practice-app/backend/api/views.py
Labels: Type: Test

#116 parity update
  practice-app/backend/api/views.py
  practice-app/frontend/index.html
Labels: enhancement

#118 add test for create investment end point
  practice-app/backend/api/tests.py
Labels: Priority: Medium, Status: Review Needed, Type: Test

#121 deliverable initialized
  deliverables/M2-Group2.md
  deliverables/M2-Group2.pdf
  design/Project Plan.jpg
Labels: Type: Documentation
