Repository bounswe/bounswe2019group2, pull requests merged in 2020-01, with the labels that each got.

#445 Bring demo related changes
  traiders/mobile/app/src/main/java/tk/traiders/MainActivity.java
  traiders/mobile/app/src/main/java/tk/traiders/components/alarm/CreateAlarmFragment.java
  traiders/mobile/app/src/main/java/tk/traiders/components/annotation/ShowAnnotationsFragment.java
  traiders/mobile/app/src/main/java/tk/traiders/components/article/ViewArticleActivity.java
  traiders/mobile/app/src/main/java/tk/traiders/components/asset/CreateAssetFragment.java
  traiders/mobile/app/src/main/java/tk/traiders/constants/AssetConstants.java
  traiders/mobile/app/src/main/java/tk/traiders/marshallers/AssetMarshaller.java
  traiders/mobile/app/src/main/java/tk/traiders/models/Asset.java
  traiders/mobile/app/src/main/java/tk/traiders/ui/investments/InvestmentsFragment.java
  traiders/mobile/app/src/main/java/tk/traiders/ui/investments/adapters/AssetAdapter.java
  traiders/mobile/app/src/main/java/tk/traiders/ui/investments/adapters/NotificationAdapter.java
  traiders/mobile/app/src/main/java/tk/traiders/ui/investments/adapters/PortfolioAdapter.java
  traiders/mobile/app/src/main/java/tk/traiders/ui/investments/children/InvestmentFragment.java
  traiders/mobile/app/src/main/res/layout/annotation_list_item.xml
  traiders/mobile/app/src/main/res/layout/asset_list_item.xml
  traiders/mobile/app/src/main/res/layout/create_asset_fragment.xml
  traiders/mobile/app/src/main/res/layout/fragment_create_alarm.xml
  traiders/mobile/app/src/main/res/layout/fragment_personal.xml
  traiders/mobile/app/src/main/res/layout/notification_list_item.xml
  traiders/mobile/app/src/main/res/layout/portfolio_item_list_item.xml
  traiders/mobile/app/src/main/res/menu/assets_menu.xml
Labels: mobile

#443 Documentation/user manual
  deliverables/user_manual.md
Labels: Status: In Progress, Type: Documentation, help wanted

#438 Final Report
  FinalProjectPlan.pdf
  FinalProjectPlanGant.pdf
  deliverables/M3-CMPE451.md
  deliverables/images/canözcan.png
  deliverables/images/enesyılmaz.png
  deliverables/images/johnwick.png
Labels: Type: Documentation
